### ISSUE TITLE
Review DB indexing of "stations" as well as RDB resources

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GageStatsServices#43]
Looking to improve responses to gagestats services. Can we:
- [ ] review tables and queries to ensure indexing is set up properly
- [ ] review the size of the RDB - perhaps that should be improved

@kjacobsen16 can capture here in the issue what endpoint seems to be struggling with the response, but as these services are expected to have significant use (potential link to the new water pages) we should give the set-up a once-over.

**Comment by HansVraga** [comment]
Looking for good response time from: https://test.streamstats.usgs.gov/gagestatsservices/stations?pageCount=10000

**Comment by HansVraga** [comment]
And this one looks good now, but a single station endpoint is the one that potentially could be slammed by the water pages. https://test.streamstats.usgs.gov/gagestatsservices/stations/552

**Comment by HansVraga** [comment]
And this one looks good now, but a single station endpoint is the one that potentially could be slammed by the water pages. https://test.streamstats.usgs.gov/gagestatsservices/stations/552

**Comment by kjacobsen16** [comment]
The largest return we'd get returned at one time is https://test.streamstats.usgs.gov/gagestatsservices/stations?pageCount=37000&includeStats=true (37000 items returned)

**Comment by kjacobsen16** [comment]
Also - this is for the SS postgresql DBs.

And the calls seems to max out between [8100](https://test.streamstats.usgs.gov/gagestatsservices/stations?pageCount=8100) and [8200](http://test.streamstats.usgs.gov/gagestatsservices/stations?pageCount=8200) stations returned.

**Comment by kjacobsen16** [comment]
@PatrickMooreUSGS @aaronstephenson  has there been any progress on this issue?

**Comment by PatrickMooreUSGS** [comment]
I have no progress to report on this issue at this time.

**Comment by aaronstephenson** [comment]
Ditto. @PatrickMooreUSGS let's aim to work on this next week.

**Comment by aaronstephenson** [comment]
@kjacobsen16 what specific database in what specific instance do you want me to look at?

![image](https://user-images.githubusercontent.com/8713712/91904059-e53e2d80-ec69-11ea-9cd2-db8ec3e8a072.png)

side question: are the two MariaDB instances still used or can we terminate them?

**Comment by kjacobsen16** [comment]
@aaronstephenson  There are a couple issues:
1. The issue mentioned here, calls to the test > StatsDB > gagestats > Stations table won't return past a certain number of stations. This is in the test postgres DB, used on the test site. It'll also be used on prod eventually, which will be at nss-v2 > StatsDB > gagestats.
2. We discovered recently that occasionally calls to nss-v2 > StatsDB > nss  hang for a bit.

There's one small part of the project that's using the Maria DBs, I plan on fixing that next fiscal year.

**Comment by aaronstephenson** [comment]
Just some initial observations as I start to dig in:

- https://test.streamstats.usgs.gov/gagestatsservices/stations?pageCount=10000 returns a 500 error
- https://test.streamstats.usgs.gov/gagestatsservices/stations/552 responds in 0.2 seconds
- https://test.streamstats.usgs.gov/gagestatsservices/stations?pageCount=37000&includeStats=true returns a 502 error

The count of objects returned isn't directly affected by indexing, instead I would guess that the problem is either some artificial cap on the count of objects able to be returned or perhaps a low timeout (this could be imposed in a few different places, either the DB or the web server or the services code or even the client code).

Indexing is a way to optimize queries by decreasing the time needed to traverse records. It _could_ affect the count of objects returned by handling queries faster, thereby retrieving more records before a timeout hits, but I think that's a separate concern, especially in the scenarios above where there don't appear to be any specific field queries that would take advantage of indexing (i.e., by use of a `WHERE` clause)... the `pageCount` query param shown is equivalent to a `LIMIT` operator (which doesn't use indexing), and `includeStats` is likely a simple lengthier `SELECT` statement with more fields (which doesn't use indexing), either in the stations table itself or joined to other tables (the latter _would_ make the query slower, tho) (of course I would need to dig into the code to know for sure)... in my opinion the big problem is why the server seems to be hitting a limit at all. Once we figure that out, we can address the speed issue.

I will need to work with a developer on the team to troubleshoot this.

**Comment by kjacobsen16** [comment]
@aaronstephenson I can look at this with you - I put together a lot of these endpoints so I should be able to show you what it's doing. They're .netcore btw

**Comment by kjacobsen16** [comment]
Noting what we found today: the change seems to have resulted from the upgrade from .netcore 2.2 to 3.1, which was pushed through on 6/15/2020. The exact fail point is https://test.streamstats.usgs.gov/gagestatsservices/stations?pageCount=8193.

Next steps: looking through breaking changes in any version updates at that point and asking Jeremy 😃
