### ISSUE TITLE
Include additional nested information in `/stations/` endpoint

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/GageStatsServices#54]
Will allow for population of gage pages without many loops of additional requests

**Comment by marsmith** [comment]
For the purposes of the gage pages it would be useful to have the following additional info in the main /stations/ request, ie: https://test.streamstats.usgs.gov/gagestatsservices/stations/11427500

In the main object: 

- replace agencyID code with agency name
- replace stationTypeID with station type name

in the characteristics object:

- need to add characteristics groups like on the old page
- nest full citation, and make sure citation is there in the first place
- add characteristic variableType name
- add characteristic unitType name

in the statistics object

- would be nice but not necessary if the statistics came back nested in their statisticsGroups
- add statistic regressionType name
- add characteristic unitType name

**Comment by kjacobsen16** [comment]
Also need to include statistic YearsofRecord

**Comment by kjacobsen16** [comment]
(checklist for myself)
In the main object:
- [x] replace agencyID code with agency name
- [x] replace stationTypeID with station type name

in the characteristics object:
- [ ] need to add characteristics groups like on the old page
- [x] nest full citation, and make sure citation is there in the first place
- [x] add characteristic variableType name
- [x] add characteristic unitType name

in the statistics object
- [ ] would be nice but not necessary if the statistics came back nested in their statisticsGroups
- [x] add statistic regressionType name
- [x] add characteristic unitType name

**Comment by kjacobsen16** [comment]
Got most of this working locally - I'll get it merged soon.

Some notes - with how the services work the best/easiest way is to include the whole object for associated IDs, so instead of a agency name, etc. it'll be an "agency" property object with all properties of the agency. Same for everything else I did.

Currently, there is no characteristic group type in the DB, so that's a separate issue if Pete and Ryan want them that will require a new DB table, etc. Grouping statistics by statistics groups is possible, but will be a bit more work and might not be worth it, so I'm leaving it out for now.

**Comment by kjacobsen16** [comment]
@marsmith most of what you asked for is live on the test services now: https://test.streamstats.usgs.gov/gagestatsservices/stations/11427500
