### ISSUE TITLE
Missing citations for characteristics

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/GageStatsServices#55]
![image](https://user-images.githubusercontent.com/6529123/87811353-8b55e580-c82c-11ea-9b1e-587c44e44b63.png)

**Comment by kjacobsen16** [comment]
Looks like it's an issue with this citation in SSDB:
![image](https://user-images.githubusercontent.com/35497731/87814071-b1798680-c828-11ea-8649-b6dc08ddeedf.png)
I wonder if it's an issue because it uses the title twice here (in GageStatsDB), so the FU script doesn't read it as the same citation:
![image](https://user-images.githubusercontent.com/35497731/87814140-cce49180-c828-11ea-90fa-a79d9624f96a.png)

I asked Ryan about these citations to see if there's a different way to cite them, since they're not technically citations.

**Comment by marsmith** [comment]
I guess it would still be good to flag these in some way, even with a -9999 so we can somehow code them on the new gage pages

**Comment by kjacobsen16** [comment]
@marsmith Ryan said he's going to delete items with that citation in the future, so I think for now we can ignore them.

I think I found a way to adapt the script so it doesn't happen again though.

**Comment by kjacobsen16** [comment]
@marsmith I ran through and updated all the stats that were using the problem citation, they all have citations now.
